  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "PMP"
  weight = 520
  identifier = "pmp"
  parent = "Certifications"

  [[main]]
  name = "CSM"
  weight = 520
  identifier = "csm"
  parent = "Certifications"

  [[main]]
  name = "Old Blog"
  weight = 300
  identifier = "Old Blog"
  url = "https://anchitkalra.wordpress.com/"
  parent = "Portfolio"

  [[footer]]
  name = "clicky"
  weight = 1
  identifier = "clicky"