  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  # [[main]]
  # name = "Portfolio"
  # weight = 300
  # identifier = "portfolio"
  # url = "/portfolio/"

  [[main]]
  name = "PMP"
  weight = 520
  identifier = "pmp"
  parent = "Certifications"

  [[main]]
  name = "CSM"
  weight = 520
  identifier = "csm"
  parent = "Certifications"

  [[footer]]
  name = "clicky"
  weight = 1
  identifier = "clicky"
  embed_code = """
    <a title="GDPR-compliant Web Analytics" href="https://clicky.com/101476222"><img alt="Clicky" src="//static.getclicky.com/media/links/badge.gif" border="0" /></a>
    <script async data-id="101476222" src="//static.getclicky.com/js"></script>
    <noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/101476222ns.gif" /></p></noscript>
    """