name: Deploy Hugo Site to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
    
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Hugo
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y hugo
        sudo apt-get install -y rsync

    - name: Build Hugo Site
      shell: bash
      run: hugo -s anchitkalrablog

    - name: Deploy to GCP VM
      shell: bash
      env:
        VM_IP: $GCP_VM_IP
        REMOTE_DIR: /usr/share/nginx/html
      run: |
        echo "STARTING DEPLOYMENT"
        ssh-keyscan $VM_IP >> ~/.ssh/known_hosts
        echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/ssh_key.pem
        chmod 0400 ~/.ssh/ssh_key.pem
        rsync -avz -e "ssh -i ~/.ssh/ssh_key.pem" anchitkalrablog/public/ anchit_kal@$VM_IP:$REMOTE_DIR

    