name: Deploy Hugo Site to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Hugo
      run: |
        sudo apt-get update
        sudo apt-get install -y hugo

    - name: Build Hugo Site
      run: hugo -s anchitkalrablog

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh && chmod 700 ~/.ssh && touch ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        ssh-keyscan -H $VM_IP >> ~/.ssh/known_hosts

    - name: Deploy to GCP VM
      env:
        VM_IP: ${{ secrets.GCP_VM_IP }}
        SSH_KEY: |
         ${{ secrets.GCP_SSH_KEY }}
        REMOTE_DIR: /var/www/html
        SSH_KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
      run: |
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        echo "$SSH_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
        rsync -avz -e "ssh -i ssh_key.pem" anchitkalrablog/public/ anchit_kal@$VM_IP:$REMOTE_DIR